# Generated by Django 4.0.6 on 2022-08-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TownList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=5)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.countylist')),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=5)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.townlist')),
            ],
        ),
    ]
